# Generated by Django 3.0.7 on 2024-11-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_studentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='matric_number',
            field=models.CharField(default=0, max_length=9),
        ),
    ]
